{
  try {
    closable.close();
  }
 catch (  Exception exception) {
    Utils.error(LOGGER,exception,"Something bad happen when closing.");
  }
}
